### PR TITLE
Add raw option

### PR DESCRIPTION
**Pull request by chtenb**
This allows to use the same dicts for outputting other formats beside tmTheme.

### CODE REVIEW

**Comment by chtenb** [comment]
@jibsen Any opinions on this PR?

**Comment by jibsen** [comment]
Thank you for the reminder!

My only objection to the change is that it feels like this need might be better served with a separate more general script than adding the functionality to this one, which servers a very specific purpose.

For instance I am using [this script](https://gist.github.com/jibsen/1ca0d3b1ecd98020739670bf09f7343d) in another project to generate theme files for a number of editors from templates and dictionaries. Would that work for your use case? or do you need the functionality of yamltotm as well?

**Comment by chtenb** [comment]
Thanks for your response. Yeah, I'm currently using it for theme generation at https://github.com/chtenb/vscode-ansi16
Some files need to be converted as-is while others need to be treated as tmTheme files. Seemed handy to me to put it in the same script, as I think it is generally fairly likely that one would also have to transform some additional files next to the tmTheme files when generating theme files for text editors, just like this case.

**Comment by jibsen** [comment]
Seems like a reasonable argument, thanks for the PR!

**Pull request merged**
